/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ps_util_PSUtil */

#ifndef _Included_com_ps_util_PSUtil
#define _Included_com_ps_util_PSUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ps_util_PSUtil
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ps_util_PSUtil_init
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_ps_util_PSUtil
 * Method:    invoke
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ps_util_PSUtil_invoke
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
